### ISSUE TITLE
Error: ws does not work in the browser. Browser clients must use the native WebSocket object

### ISSUE THREAD

**Issue by fanksy** [flaviodelgrosso/electron-forge-react-vite-boilerplate#1]
I used puppeteer to connect to the browser websocket , and an error occurred. 

Please check this. 

this is related issue.
https://github.com/perawallet/connect/issues/101

I added "global.WebSocket": "globalThis.WebSocket", but it didn't work.

```
Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new sfA (/Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:548:6313)
    at /Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:552:427
    at new Promise (<anonymous>)
    at ML.create (/Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:552:399)
    at lfA.createCdpSocketConnection (/Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:556:2343)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async lfA.launch (/Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:556:1465)
    at async /Users/nolan/Work/JsProjects/electron-forge-react-vite-boilerplate/.vite/build/main-b0efc4c7.js:660:99124
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:89452)
```

**Comment by flaviodelgrosso** [comment]
@fanksy Hello, thanks for opening issue. I'll try to investigate about that.

**Comment by flaviodelgrosso** [comment]
In the meantime, I've upgraded the core dependencies and `@electron/forge` to the latest version. Can you try to update and check if the problem persists?

Can you also provide a reproducible case for this issue?
Thanks

**Comment by fanksy** [comment]
I replaced puppeteer with playwright, it works well.

Thanks for your attention. I really appreciate for your work.
